Fix chaos test docker flaky management (#325)
Chaos tests sometime fail because of:


```bash
    chaos_test.go:198: 🐒 Chaos Monkey: Stopped PostgreSQL
    chaos_test.go:159: 
        	Error Trace:	/home/runner/work/dbos-transact-golang/dbos-transact-golang/chaos_tests/chaos_test.go:159
        	            				/home/runner/work/dbos-transact-golang/dbos-transact-golang/chaos_tests/chaos_test.go:205
        	            				/opt/hostedtoolcache/go/1.25.7/x64/src/runtime/asm_amd64.s:1693
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestChaosQueues
        	Messages:   	Failed to start postgres: {"time":"2026-02-23T22:16:11.898958477Z","level":"INFO","msg":"Attempting to create a Docker Postgres container..."}
        	            	Error: failed to start existing container: Error response from daemon: container is marked for removal and cannot be started
```

This PR handles postgres start/stop failures more thoroughly.